Fix error when `--headers` option is not used.
This fix avoids passing `None` rather than an empty dictionary
to `Request(...)` which otherwise leads to this error:

    ERROR: 'NoneType' object has no attribute 'items'

which has the traceback:

    [...snip...]
      File "/<path>/zipdump/urlstream.py", line 69, in open
        return urlstream(Request(method + basepath + query, headers=headers))
      File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__
        for key, value in headers.items():
    AttributeError: 'NoneType' object has no attribute 'items'

(Tested with `./zipdump.py --quick --debug https://downloads.tuxfamily.org/godotengine/4.0/rc5/Godot_v4.0-rc5_export_templates.tpz`.)